### PR TITLE
CommonJS Changes

### PR DESCRIPTION
**Pull request by seanadkinson**
Obviously you don't want this PR as-is (since the README is changed), but let me know what you think about the `vars.js -> createClass.js` changes, since that was really the area that wasn't working for me.

### CODE REVIEW

**Comment by jhudson8** [comment]
I think these changes are going in the right direction.

The name change is fine - I had it with that name because it was where the react instance was set previously
I'm find with referencing the modules through a central entry point rather than the sub modules directly
I do not want to remove support for AMD though - think you can get that straight?

**Comment by seanadkinson** [comment]
Yeah, let me look into that.

**Comment by jhudson8** [comment]
depending on the difficulty, I'm not opposed to just supporting CommonJS - but it would be ideal to support all.

**Comment by seanadkinson** [comment]
Haven't been able to look at this yet, but might have a chance today or tomorrow.

**Comment by jhudson8** [comment]
see comments on https://github.com/jhudson8/react-chartjs/issues/4

**Pull request closed without merging**
