### PR TITLE
Fix: unknown prop 'redraw' warning in React v15.2

### PR DESCRIPTION
**Pull request by strawbrary**
React v15.2 emits the following warning when trying to use 'redraw' mode.
`Warning: Unknown prop `redraw` on <canvas> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

### CODE REVIEW

**Comment by austinpray** [comment]
Thank you!

**Comment by pablen** [comment]
Thanks! any ETA for publishing this fix to npm?

**Comment by austinpray** [comment]
Published as 0.8.0

**Comment by dallonf** [comment]
Can you also merge this to the "v2" branch?

**Pull request merged**
