### PR TITLE
Use create-react-class to avoid warning

### LINKED ISSUE #183: React.createClass is deprecated
From the console warning: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

### PR DESCRIPTION
**Pull request by merlinstardust**
Fixes #183

### CODE REVIEW

**Comment by davideghz** [comment]
When will this fix be merged?

**Comment by filipebarcos** [comment]
Why not change components to use js classes instead?

**Comment by merlinstardust** [comment]
@filipebarcos This is a faster fix to get the warning removed. Replacing it with JS classes will require an actual refactor

**Comment by igorshmukler** [comment]
@merlinpatt thank you for the commit. would love to see this merged, so the warning will be gone. IMHO, in a long-term refactoring perhaps is better. however, in a near-term, eliminating the warning will definitely be beneficial, to me, at least.

**Comment by msteward** [comment]
Agree that this is the simplest low-risk fix for the short term to help users of the library continue to use it whilst preparing for React 16

**Comment by dmason30** [comment]
@arjunskumar47 @austinpray can we get this in as a priority?

**Comment by rgranger** [comment]
Hi guys ! Can we get this into the master branch ? So people using React 16 can also use this module ?

**Comment by kdejaeger** [comment]
Is there another package on npm compatible with this fix? Kinda need it for a react update to v16.

**Comment by rgranger** [comment]
https://github.com/jerairrest/react-chartjs-2

Look for equivalent packages on npms.io ;)

**Pull request merged**
