### PR TITLE
Updated for React 0.14, fixed when updating labels

### PR DESCRIPTION
**Pull request by zackify**
Some of your code isn't in the latest version on npm, like nextProps.redraw is this.props.redraw on npm, spent 30 minutes figuring that out lol. This should fix everything.

### CODE REVIEW

**Comment by austinpray** [comment]
Isn't this forgetting to add `react-dom` as a peerDependency?

**Comment by zackify** [comment]
@austinpray you're right. After making this PR I saw how there is no activity on this repo and forgot about it.

**Comment by sspross** [comment]
öhm so what's going on here? things are fixed but v0.7.1 is no available on npm. how can we help?

**Comment by joshhornby** [comment]
That was my mistake, I have released 0.7.2 https://github.com/jhudson8/react-chartjs/tree/0.7.2.

**Comment by joshhornby** [comment]
@jhudson8 Can you please update NPM. Thanks

**Comment by sspross** [comment]
@jhudson8 is there still hope or should we switch over to https://github.com/gregthebusker/rc-chartjs?

**Pull request closed without merging**
