### PR TITLE
Make react-charts compatible with react@0.14.0-rc1

### PR DESCRIPTION
**Pull request by dmr**

### CODE REVIEW

**Comment by dmr** [comment]
But react 0.14 isn't released yet and it might break compatibility so I'm not sure if this should be merged yet

**Comment by dmr** [comment]
package.json refers a "test" command but I don't see any tests

**Comment by gustavoguichard** [comment]
I think this should be merged now because react 0.14 was released already.
And also, `getDOMNode()` was already deprecated in react 0.13.

**Comment by Anahkiasen** [comment]
:+1:

**Comment by santiagoaguiar** [comment]
+1 needing this one to move forward to 0.14.

**Comment by tomfairbs** [comment]
Yep, +1 from me as well. Would also be a good idea to update the compiled versions in /dist.

**Comment by sspross** [comment]
+1

**Comment by siemya** [comment]
+1

**Comment by dmr** [comment]
Do I read correctly that this pull request is outdated and peerDependencies are the way to got and #54 already added all the things that I didn't?

**Comment by eanplatter** [comment]
@dmr yeah, it looks like #54 covers it all.

**Comment by dmr** [comment]
Well, then we can just close this :)

**Pull request closed without merging**
