### PR TITLE
Some es6 conversions, removed deprecated methods and added support for horizontal bar

### PR DESCRIPTION
**Pull request by Jareechang**
as stated in the title, plenty of changes.

Main Changes: 
1. Some ES6 conversion
2. Removed  **Deprecated Methods** 
   - `PointsAtEvent(e)`, `AddData` and `removeData`
3. Add support for new Methods 
   - `render`,`getElementAtEvent`, `getElementsAtEvent`, `getDatasetAtEvent`, `getDatasetMeta`
4. Added support for **horizontal bars**
   - moved **ternary expression** into a **dictionary method** — `convertToValidChartType`

### CODE REVIEW

**Comment by Jareechang** [comment]
hey @austinpray, can you have a look at this PR when you get chance please 😄, thank you!

**Comment by austinpray** [comment]
Yes I'll take a look!

**Comment by chaliy** [comment]
Any chance?

**Comment by benmccann** [comment]
@Jareechang this PR needs to be rebased

**Comment by Jareechang** [comment]
@benmccann, ok. I will have a look later this week.

**Comment by Jareechang** [comment]
hey @benmccann, I may have to nuke these changes and PR on top of the latest code base. 

There are just too many merge conflicts for me to properly track what is happening. Please close this PR. Thanks.

**Comment by benmccann** [comment]
Ok. Thanks for that. And sorry for the delay in getting your PR reviewed

Btw, you had 4 changes listed in the description. If you're able to open new PRs for these, can you do them as separate PRs?

Thanks again

**Pull request closed without merging**
