### PR TITLE
(feat) Chart.js 2.0-dev compatibility

### PR DESCRIPTION
**Pull request by danmolitor**
After reading about Chart.js 2.0's performance upgrades, I've updated react-chartjs to be compatible with the Chart.js most up to date 2.0-dev branch, including the new bubble and scatter charts. By moving from 1.0.2 to 2.0, the time it takes a simple line-chart to render has dropped significantly. 

Since people may still want to use Chart.js v1.0.2., if you don't want to merge yet people can still use this version by updating their dependencies in their project's package.json to:

"chart.js": "git://github.com/danmolitor/Chart.js.git#v2.0-dev",
"react-chartjs": "git+https://github.com/danmolitor/react-chartjs.git"

I've attached a image showing the original charts using Chart.js v2.0-dev. 

react-chartjs2

### CODE REVIEW

**Comment by RamonBeast** [comment]
+1

**Comment by austinpray** [comment]
Thank you for the PR!

I made a branch here: https://github.com/jhudson8/react-chartjs/tree/chartjs-v2

 Can you resubmit this PR against this branch so we can consolidate effort towards v2?

**Comment by danmolitor** [comment]
Definitely! I'll do that now.

**Comment by danmolitor** [comment]
Hey Austin!

Just making sure I do this correctly, is the best way to do this by closing this PR, and reopening a new one to the new branch?

**Comment by austinpray** [comment]
Yep, close and recreate the PR.

related: https://github.com/isaacs/github/issues/18

**Pull request closed without merging**
