### PR TITLE
React 0.14

### PR DESCRIPTION
**Pull request by oliger**
Same as https://github.com/jhudson8/react-chartjs/pull/48 but added react-dom in peerDependencies.

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Could this be merged and tagged? Currently `react-chartjs` is the only one of the libs I use that still throws warnings in 0.14

**Comment by eanplatter** [comment]
Same here, +1

**Comment by mrpapercut** [comment]
Same here, waiting for this pull request to be merged

**Comment by gregthebusker** [comment]
This project doesn't seem to be maintained any more.  You can use this package instead, which includes this pull request.
https://www.npmjs.com/package/rc-chartjs

**Comment by mrpapercut** [comment]
@gregthebusker will you be actively maintaining the package (keeping up to date with new react releases, eliminating bugs), actively developing (adding new features etc) or is it just going to be the current version, including pull request?

**Comment by gregthebusker** [comment]
It depends what you mean by active. I'll be actively making sure it's up to
date with the most recent version of react, but I'm going to rely on pull
requests for bug and new features.

**Comment by mrpapercut** [comment]
Alright, thanks for the reply!

**Comment by austinpray** [comment]
@jhudson8 would you consider adding some more contributors to the repo?

**Comment by jhudson8** [comment]
@austinpray I've added you.  Thanks for helping out

**Pull request merged**
