### PR TITLE
Fix: unknown prop 'redraw' warning in React v15.2

### PR DESCRIPTION
**Pull request by michae1**
Transfer of this commit https://github.com/reactjs/react-chartjs/commit/0c34a416d191a2289f1c1dd290d49c5f8e8b570c

### CODE REVIEW

**Comment by MikeSha** [comment]
Hi guys! Would it be accepted? Thanks

**Comment by arjunskumar47** [comment]
Hi @MikeSha 

We're working on a plan to fix the existing bugs and `chartjs-v2` release. This should be reviewed soon and released along with other critical issues that are to be addressed.

**Comment by MikeSha** [comment]
@arjunskumar47
Thank you

**Comment by dmason30** [comment]
@austinpray Since you just merged the `createClass` fix in can we also get this one in without waiting for the official release (been around since `react@15.2`).

**Comment by benmccann** [comment]
This should be closed as a duplicate of https://github.com/reactjs/react-chartjs/pull/142

**Pull request closed without merging**
